FROM quay.io/keycloak/keycloak:26.1.4

ARG BUILD_DATE
ARG GIT_COMMIT
LABEL org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.revision="${GIT_COMMIT}" \
      org.opencontainers.image.version="26.1.4" \
    org.opencontainers.image.title="gofr-keycloak" \
      org.opencontainers.image.description="Ephemeral Keycloak image for GOFR sec dev verification"

COPY docker/keycloak/gofr-dev-realm.json /opt/keycloak/data/import/gofr-dev-realm.json

ENV KC_HEALTH_ENABLED=true \
    KC_HTTP_ENABLED=true

EXPOSE 8080 9000

CMD ["start-dev", "--import-realm"]